# Generated by Django 2.0.3 on 2018-03-17 18:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code_block', wagtail.core.blocks.StructBlock((('code', wagtail.core.blocks.TextBlock(required=True)), ('language', wagtail.core.blocks.CharBlock(required=False)), ('line_number', wagtail.core.blocks.IntegerBlock(required=False))))), ('two_columns', wagtail.core.blocks.StructBlock((('left_side_size', wagtail.core.blocks.IntegerBlock(default=7)), ('left_column', wagtail.core.blocks.StreamBlock((('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code', wagtail.core.blocks.StructBlock((('code', wagtail.core.blocks.TextBlock(required=True)), ('language', wagtail.core.blocks.CharBlock(required=False)), ('line_number', wagtail.core.blocks.IntegerBlock(required=False)))))), icon='arrow-left', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock((('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('code', wagtail.core.blocks.StructBlock((('code', wagtail.core.blocks.TextBlock(required=True)), ('language', wagtail.core.blocks.CharBlock(required=False)), ('line_number', wagtail.core.blocks.IntegerBlock(required=False)))))), icon='arrow-right', label='Right column content'))))), ('link_block', wagtail.core.blocks.StructBlock((('featured_pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='featured_page'))),))))),
        ),
    ]
