# Generated by Django 2.0.3 on 2018-04-02 16:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180317_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('icon_block', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('font_awesome_class', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('svg', wagtail.core.blocks.TextBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False))))), ('link_block', wagtail.core.blocks.StructBlock((('featured_pages', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='featured_page'))),))))),
        ),
    ]
