# Generated by Django 2.0.3 on 2018-04-07 13:45

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180402_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
