# Generated by Django 2.0.3 on 2018-04-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='include_mathjax',
            field=models.BooleanField(default=False, verbose_name='Include mathjax'),
            preserve_default=False,
        ),
    ]
